### ISSUE TITLE
WIFI took so long to search for a network when start the device

### ISSUE THREAD

**Issue by bunnybavros** [devboloji/Infinix-Hackintosh-Opencore-Guide#23]
I have got no idea how is this happen, maybe it is because of the ventura or something,
but things took so long to start, such as the control panel, wifi and etc.

Is this normal?
Anyone else facing this problem?

BTW, this is the video of the issue that I have found; I recorded it right after the Mac booted up and it tooks almost 2-3 mins for everything to start up.
**Link:** https://youtu.be/NME3dSHVKrw
_____

**Spec: Infinix INBook X1 Pro**
**CPU**
Intel Core i7-1065G7

**GPU**
Intel Iris Plus Graphics G7

**RAM**
16 GB LPDDR4x On Board
3200 MHz

**Comment by devboloji** [comment]
@bunnybavros Actually the issue is common for Every Hackintosh user. Fix is, just reset nvram once. Then stick with ONE EFI, don't change EFI.
I cannot do anything about it, The problem is with [AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.1.0) and infinix device.😉
Or update the AirportItlwm to alpha.

**Comment by bunnybavros** [comment]
Now I get it!
Thank you for the details; they are really clear and clarify what the actual issue is.

By the way, the video was just recorded by the built-in Apple, haha!

**Comment by bunnybavros** [comment]
I heard that good news, now i am so excited! haha
